version: "3"

services:
    postgres:
        image: postgres:16
        container_name: bla-postgresql
        environment:
            POSTGRES_DB: database
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./postgresql:/var/lib/postgresql/data
    redis:
        image: redis:6
        container_name: bla-redis
        ports:
            - "6379:6379"
